services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api

  api:
    image: node:20
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
    command: npx json-server db.json --port 3001 --host 0.0.0.0
    ports:
      - '3001:3001'
